"""Durable adapters for private messaging channels."""

from .auth import AuthorizationPolicy, AuthorizationResult
from .formatting import TELEGRAM_TEXT_LIMIT, chunk_outbound, chunk_text, safe_html, utf16_units
from .models import (
    AuthDecision,
    ChannelAdapter,
    ChannelEnvelope,
    InboxRecord,
    InboxStatus,
    IngestResult,
    MessageOperation,
    OutboundMessage,
    OutboxRecord,
    OutboxStatus,
    ParseMode,
    Platform,
    RemoteReceipt,
)
from .processor import ChannelHandler, ChannelProcessor, OutboundPreparer
from .slack import (
    SLACK_BLOCK_LIMIT,
    SLACK_HEADER_TEXT_LIMIT,
    SLACK_SECTION_TEXT_LIMIT,
    SLACK_TEXT_LIMIT,
    NormalizedSlackEvent,
    SlackAdapter,
    SlackAPIError,
    SlackConnectionError,
    SlackError,
    SlackTransportError,
    SlackWebClient,
    SocketTransport,
    normalize_slack_event,
    valid_slack_blocks,
)
from .store import (
    ChannelStore,
    ChannelStoreClosedError,
    ChannelStoreError,
    ChannelTransitionError,
)
from .telegram import (
    TELEGRAM_UPDATE_ID_EPOCH_RESET_AFTER,
    NormalizedTelegramUpdate,
    TelegramAdapter,
    TelegramAPIError,
    TelegramConflictError,
    TelegramError,
    TelegramOffsetState,
    TelegramOffsetStateStore,
    TelegramTransportError,
    normalize_telegram_update,
)

__all__ = [
    "TELEGRAM_TEXT_LIMIT",
    "TELEGRAM_UPDATE_ID_EPOCH_RESET_AFTER",
    "SLACK_BLOCK_LIMIT",
    "SLACK_HEADER_TEXT_LIMIT",
    "SLACK_SECTION_TEXT_LIMIT",
    "SLACK_TEXT_LIMIT",
    "SlackAPIError",
    "SlackAdapter",
    "SlackConnectionError",
    "SlackError",
    "SlackTransportError",
    "SlackWebClient",
    "SocketTransport",
    "TelegramAPIError",
    "TelegramAdapter",
    "TelegramConflictError",
    "TelegramError",
    "TelegramOffsetState",
    "TelegramOffsetStateStore",
    "TelegramTransportError",
    "AuthDecision",
    "AuthorizationPolicy",
    "AuthorizationResult",
    "ChannelAdapter",
    "ChannelEnvelope",
    "ChannelHandler",
    "ChannelProcessor",
    "ChannelStore",
    "ChannelStoreClosedError",
    "ChannelStoreError",
    "ChannelTransitionError",
    "InboxRecord",
    "InboxStatus",
    "IngestResult",
    "MessageOperation",
    "NormalizedTelegramUpdate",
    "NormalizedSlackEvent",
    "OutboundMessage",
    "OutboundPreparer",
    "OutboxRecord",
    "OutboxStatus",
    "ParseMode",
    "Platform",
    "RemoteReceipt",
    "chunk_outbound",
    "chunk_text",
    "normalize_telegram_update",
    "normalize_slack_event",
    "safe_html",
    "utf16_units",
    "valid_slack_blocks",
]
